### ISSUE TITLE
Trim input in `Edit Text`

### ISSUE THREAD

**Issue by ktalanda** [rspective/voucherify-android-sdk#22]
I accidentally put ` Testing7fjWdr` with space at the beggining into our input. We could trim the input before sending via REST so we can avoid those types of errors.

**Comment by polok** [comment]
yea, good idea!

**Comment by ktalanda** [comment]
addressed by https://github.com/voucherifyio/voucherify-android-sdk/pull/39

**Comment by polok** [comment]
Also done by @ktalanda !
