### ISSUE TITLE
Add static code analisys

### ISSUE THREAD

**Issue by ktalanda** [rspective/voucherify-android-sdk#26]
http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code/

**Comment by ktalanda** [comment]
addressed by 
https://github.com/voucherifyio/voucherify-android-sdk/pull/35
https://github.com/voucherifyio/voucherify-android-sdk/pull/34

**Comment by polok** [comment]
Done! 👍 goes to @ktalanda
